// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Gem struct {
	ID            uuid.UUID
	GemCategoryID uuid.UUID
	GemName       string
	Description   string
	Instruction   string
	Coordinates   []float64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type GemCategory struct {
	ID           uuid.UUID
	CategoryName string
	Slug         string
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
